// Target the local FastAPI container
const API_BASE = "http://localhost:8000/api/v1";

export async function fetchSchema() {
    const res = await fetch(`${API_BASE}/documents/schema`);
    if (!res.ok) throw new Error(`Backend unavailable. Status: ${res.status}`);
    const data = await res.json();
    return data.modules;
}

export async function generateAndDownload(payload, fallbackFilename) {
    const response = await fetch(`${API_BASE}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || "Engine compilation failure.");
    }

    // Process binary stream into a downloadable file
    const blob = await response.blob();
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    
    // Extract exact filename generated by the backend
    const contentDisposition = response.headers.get('Content-Disposition');
    let filename = fallbackFilename;
    if (contentDisposition && contentDisposition.includes('filename="')) {
        filename = contentDisposition.split('filename="')[1].split('"')[0];
    }
    
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    
    // Memory cleanup
    a.remove();
    window.URL.revokeObjectURL(url); 
    
    return filename;
}