
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cert_engine_api
    volumes:
      - ./app:/workspace/app
      - ./templates:/workspace/templates
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USER1_USERNAME=${USER1_USERNAME}
      - USER1_PASSWORD=${USER1_PASSWORD}
      - USER2_USERNAME=${USER2_USERNAME}
      - USER2_PASSWORD=${USER2_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: cert_engine_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=http://api:8000
    container_name: cert_engine_ui
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
